"""Prompt clause for long-running / external shell jobs (OTA, Expo, EAS)."""

LONG_RUNNING_SHELL_CLAUSE = (
    "Long-running ship jobs (OTA canary, Expo export/bundle, EAS update): "
    "do NOT block on Cursor shellToolCall for the heavy job — Cursor only emits shell "
    "stdout when the tool finishes, so the operator cannot watch mid-run progress, and "
    "Axon may stale-fail the Lead run (~30–90m idle) while Expo/EAS continues orphaned. "
    "Start once with the PATH helper (works from any cwd, including DashPro): "
    "`axon-agent-terminal-job --workspace <workspace_id> -- <command>` "
    "(example: `axon-agent-terminal-job --workspace workspace_dashpro -- npm run ota:canary`). "
    "If that command is missing, run "
    "`./scripts/ops/install-bin-wrappers.sh` from the axon-watch repo, or call the script by "
    "absolute path under axon-watch `scripts/ops/axon-agent-terminal-job.sh`. "
    "Do not use a relative `./scripts/ops/...` path from a DashPro checkout — it will not exist. "
    "Never run bare `npm run ota:canary` / `eas update` as a blocking Cursor shell tool. "
    "If you are running from a disposable worker checkout, do not treat missing `.git` or "
    "`fatal: not a git repository` there as proof the real workspace is unavailable; "
    "the helper resolves and runs inside the real workspace by `--workspace`. "
    "For ship tasks, enqueue the helper once and let the real-workspace command perform "
    "its own branch/dirty/auth guards; if chat streaming cannot be attached, retry with "
    "`--no-stream` rather than blocking the dispatch. "
    "The helper enqueues an Axon-owned PTY job; live chat `:::terminal` streaming requires an "
    "active Lane B/worker stream target and control-plane restart after deploy. "
    "Poll job status sparsely via "
    "`GET /api/workspaces/<workspace_id>/terminal/agent-jobs/<job_id>` "
    "(or `axon-agent-terminal-job --status <job_id> --workspace <id>`), about once per 30–60s. "
    "When the job finishes, report the Expo Update group/branch (operator-canary) — not EAS Build. "
    "Do not launch a second heavy Expo/Metro/typecheck heap when one is already running."
)
