//! Packaged desktop runtime: XDG paths, env bootstrap, sidecar lifecycle.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;

use serde::Serialize;
use uuid::Uuid;

pub const CONTROL_PLANE_PORT: u16 = 8787;
pub const WATCH_PORT: u16 = 8788;

#[derive(Debug, Clone, Serialize)]
pub struct DesktopPaths {
    pub config_dir: PathBuf,
    pub state_dir: PathBuf,
    pub deployment_env: PathBuf,
}

pub struct SidecarSet {
    pub watch: Option<Child>,
    pub control_plane: Option<Child>,
}

pub static SIDECARS: Mutex<Option<SidecarSet>> = Mutex::new(None);

pub fn xdg_paths() -> DesktopPaths {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
    let config_dir = PathBuf::from(format!("{home}/.config/axon-watch"));
    let state_dir = PathBuf::from(format!("{home}/.local/share/axon-watch/state"));
    let deployment_env = config_dir.join("deployment.env");
    DesktopPaths {
        config_dir,
        state_dir,
        deployment_env,
    }
}

pub fn ensure_runtime_dirs(paths: &DesktopPaths) -> std::io::Result<()> {
    fs::create_dir_all(&paths.config_dir)?;
    fs::create_dir_all(&paths.state_dir)?;
    fs::create_dir_all(paths.state_dir.join("tunnel"))?;
    Ok(())
}

pub fn read_env_value(contents: &str, key: &str) -> Option<String> {
    contents.lines().find_map(|line| {
        let line = line.trim().strip_prefix("export ").unwrap_or(line.trim());
        let (candidate, value) = line.split_once('=')?;
        if candidate.trim() != key {
            return None;
        }
        let value = value.trim().trim_matches(['\'', '"']);
        (!value.is_empty() && value != "replace-me").then(|| value.to_string())
    })
}

pub fn ensure_deployment_env(paths: &DesktopPaths) -> std::io::Result<String> {
    ensure_runtime_dirs(paths)?;
    if paths.deployment_env.is_file() {
        let contents = fs::read_to_string(&paths.deployment_env)?;
        if let Some(token) = read_env_value(&contents, "AXON_WATCH_OPERATOR_TOKEN") {
            return Ok(token);
        }
    }
    let token = format!(
        "{}{}",
        Uuid::new_v4().simple(),
        Uuid::new_v4().simple()
    );
    let session_secret = Uuid::new_v4().simple().to_string();
    let body = format!(
        "# Generated by VAXON desktop first-run\n\
AXON_WATCH_DEPLOYMENT_MODE=desktop\n\
AXON_WATCH_BIND_HOST=127.0.0.1\n\
AXON_WATCH_CONTROL_PLANE_PORT={CONTROL_PLANE_PORT}\n\
AXON_WATCH_WATCH_SERVICE_PORT={WATCH_PORT}\n\
AXON_WATCH_STATE_DIR={state}\n\
AXON_WATCH_WATCH_SERVICE_BASE_URL=http://127.0.0.1:{WATCH_PORT}\n\
AXON_WATCH_PUBLIC_BASE_URL=http://127.0.0.1:{CONTROL_PLANE_PORT}\n\
AXON_WATCH_AUTH_MODE=local_token\n\
AXON_WATCH_AUTH_ALLOW_LOOPBACK=0\n\
AXON_WATCH_OPERATOR_TOKEN={token}\n\
AXON_WATCH_DESKTOP_SESSION_SECRET={session}\n",
        state = paths.state_dir.display(),
        token = token,
        session = session_secret,
    );
    let mut file = fs::File::create(&paths.deployment_env)?;
    file.write_all(body.as_bytes())?;
    Ok(token)
}

pub fn operator_token_from_env_file(path: &Path) -> Option<String> {
    let contents = fs::read_to_string(path).ok()?;
    read_env_value(&contents, "AXON_WATCH_OPERATOR_TOKEN")
}

fn resource_sidecar(name: &str) -> Option<PathBuf> {
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let triple = std::env::var("AXON_DESKTOP_TARGET_TRIPLE")
                .unwrap_or_else(|_| "x86_64-unknown-linux-gnu".into());
            let candidates = [
                dir.join(name),
                dir.join(format!("{name}-{triple}")),
                dir.join("binaries").join(name),
                dir.join("binaries").join(format!("{name}-{triple}")),
            ];
            for candidate in candidates {
                if candidate.is_file() {
                    return Some(candidate);
                }
            }
        }
    }
    let triple = std::env::var("AXON_DESKTOP_TARGET_TRIPLE")
        .unwrap_or_else(|_| "x86_64-unknown-linux-gnu".into());
    let named = format!("{name}-{triple}");
    for candidate in [
        PathBuf::from(format!("apps/console-desktop/src-tauri/binaries/{named}")),
        PathBuf::from(format!("binaries/{named}")),
    ] {
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

fn apply_common_env(cmd: &mut Command, paths: &DesktopPaths, service: &str, port: u16) {
    cmd.env("AXON_WATCH_BIND_HOST", "127.0.0.1")
        .env("AXON_WATCH_STATE_DIR", &paths.state_dir)
        .env(
            "AXON_WATCH_WATCH_SERVICE_BASE_URL",
            format!("http://127.0.0.1:{WATCH_PORT}"),
        )
        .env("AXON_WATCH_DEPLOYMENT_MODE", "desktop")
        .env("AXON_WATCH_AUTH_MODE", "local_token")
        .env("AXON_WATCH_AUTH_ALLOW_LOOPBACK", "0")
        .env(
            if service == "control-plane" {
                "AXON_WATCH_CONTROL_PLANE_PORT"
            } else {
                "AXON_WATCH_WATCH_SERVICE_PORT"
            },
            port.to_string(),
        );
    if let Some(token) = operator_token_from_env_file(&paths.deployment_env) {
        cmd.env("AXON_WATCH_OPERATOR_TOKEN", token);
    }
    if let Ok(contents) = fs::read_to_string(&paths.deployment_env) {
        if let Some(secret) = read_env_value(&contents, "AXON_WATCH_DESKTOP_SESSION_SECRET") {
            cmd.env("AXON_WATCH_DESKTOP_SESSION_SECRET", secret);
        }
    }
    if service == "control-plane" {
        if let Ok(dist) = std::env::var("AXON_WATCH_CONSOLE_DIST") {
            cmd.env("AXON_WATCH_CONSOLE_DIST", dist);
        } else if let Ok(exe) = std::env::current_exe() {
            if let Some(dir) = exe.parent() {
                let dist = dir.join("console-web-dist");
                if dist.is_dir() {
                    cmd.env("AXON_WATCH_CONSOLE_DIST", dist);
                }
            }
        }
    }
}

fn spawn_python_service(service: &str, paths: &DesktopPaths, port: u16) -> std::io::Result<Child> {
    let python = std::env::var("AXON_WATCH_PYTHON").unwrap_or_else(|_| "python3".into());
    let repo = std::env::var("AXON_WATCH_REPO_ROOT").unwrap_or_else(|_| {
        std::env::current_dir()
            .unwrap_or_else(|_| PathBuf::from("."))
            .display()
            .to_string()
    });
    let cwd = if service == "control-plane" {
        PathBuf::from(&repo).join("services/control-plane")
    } else {
        PathBuf::from(&repo).join("services/axon-watch")
    };
    let console_dist = PathBuf::from(&repo).join("apps/console-web/dist");
    let mut cmd = Command::new(&python);
    cmd.current_dir(&cwd)
        .env("AXON_WATCH_REPO_ROOT", &repo)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    apply_common_env(&mut cmd, paths, service, port);
    if service == "control-plane" && console_dist.is_dir() {
        cmd.env("AXON_WATCH_CONSOLE_DIST", console_dist);
    }
    cmd.args([
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "127.0.0.1",
        "--port",
        &port.to_string(),
    ]);
    cmd.spawn()
}

fn spawn_sidecar_binary(
    path: &Path,
    paths: &DesktopPaths,
    service: &str,
    port: u16,
) -> std::io::Result<Child> {
    let mut cmd = Command::new(path);
    cmd.stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    apply_common_env(&mut cmd, paths, service, port);
    cmd.spawn()
}

pub fn start_sidecars(paths: &DesktopPaths) -> Result<(), String> {
    let mut guard = SIDECARS.lock().map_err(|e| e.to_string())?;
    if guard.is_some() {
        return Ok(());
    }

    let watch = if let Some(bin) = resource_sidecar("axon-watch-sidecar") {
        spawn_sidecar_binary(&bin, paths, "axon-watch", WATCH_PORT)
            .map_err(|e| format!("failed to start watch sidecar: {e}"))?
    } else {
        spawn_python_service("axon-watch", paths, WATCH_PORT)
            .map_err(|e| format!("failed to start watch via python: {e}"))?
    };

    let control_plane = if let Some(bin) = resource_sidecar("axon-control-plane-sidecar") {
        spawn_sidecar_binary(&bin, paths, "control-plane", CONTROL_PLANE_PORT)
            .map_err(|e| format!("failed to start control-plane sidecar: {e}"))?
    } else {
        spawn_python_service("control-plane", paths, CONTROL_PLANE_PORT)
            .map_err(|e| format!("failed to start control-plane via python: {e}"))?
    };

    *guard = Some(SidecarSet {
        watch: Some(watch),
        control_plane: Some(control_plane),
    });
    Ok(())
}

pub fn stop_sidecars() {
    if let Ok(mut guard) = SIDECARS.lock() {
        if let Some(mut set) = guard.take() {
            if let Some(mut child) = set.watch.take() {
                let _ = child.kill();
                let _ = child.wait();
            }
            if let Some(mut child) = set.control_plane.take() {
                let _ = child.kill();
                let _ = child.wait();
            }
        }
    }
}

pub fn control_plane_url() -> String {
    format!("http://127.0.0.1:{CONTROL_PLANE_PORT}/")
}

#[cfg(test)]
mod tests {
    use super::read_env_value;

    #[test]
    fn parses_operator_token_line() {
        let contents = "AXON_WATCH_OPERATOR_TOKEN=abc123\n";
        assert_eq!(
            read_env_value(contents, "AXON_WATCH_OPERATOR_TOKEN").as_deref(),
            Some("abc123")
        );
    }
}
