<script setup lang="ts">
import BriefingSurfaceFollowupPrompt from '../../features/kairo-conversation/BriefingSurfaceFollowupPrompt.vue';
import { useAgentDockComposer } from '../../composables/useAgentDockComposer';
import AgentDockComposerImageLightbox from './agent-dock/AgentDockComposerImageLightbox.vue';
import AgentDockComposerInput from './agent-dock/AgentDockComposerInput.vue';
import AgentDockComposerToolbar from './agent-dock/AgentDockComposerToolbar.vue';
import AgentDockApprovalBanner from './agent-dock/AgentDockApprovalBanner.vue';
import AgentDockDebugReproduceBanner from './agent-dock/AgentDockDebugReproduceBanner.vue';
import AgentDockFullAccessConsent from './agent-dock/AgentDockFullAccessConsent.vue';
import AgentDockKairoComposerFooter from './agent-dock/AgentDockKairoComposerFooter.vue';

const {
  MODE_OPTIONS,
  OPERATOR_PERSONA_NAME,
  activeMode,
  attachmentChips,
  autoModelRow,
  autoToggleChecked,
  canSubmitComposer,
  canConvertInstructions,
  cancelFullAccessConsent,
  convertDraftToInstructions,
  closeAddModelsPanel,
  closeComposerImageLightbox,
  composerActivityChips,
  composerDraftModel,
  composerImages,
  composerMode,
  debugReproduceRequest,
  composerPlaceholder,
  composerPickerRows,
  composerQueueHint,
  composerShellClasses,
  composerSubmitLabel,
  confirmFullAccessConsent,
  attachFilesMedia,
  contextIde,
  contextPinned,
  contextSelection,
  contextTerminal,
  contextWorkspace,
  cursorAuthLine,
  cursorCatalogCount,
  cursorCatalogStatus,
  cursorCatalogTotal,
  cursorManageRows,
  cursorStaleWarning,
  enlargedComposerImage,
  executionAccessHint,
  extraPinnedRows,
  fullAccessConsentChecked,
  handleApproveRun,
  handleComposerDragLeave,
  handleComposerDragOver,
  handleComposerDrop,
  handleComposerKeydown,
  handleComposerPaste,
  handleDebugReproduceDismiss,
  handleDebugReproduceProceed,
  handleRejectRun,
  handleResumeRun,
  handleSteer,
  handleSteerQueuedMessage,
  handleStopRun,
  handleSubmit,
  hasTerminalSnippet,
  setInputRef,
  isFullAccessAgent,
  kairoConversationError,
  kairoConversationReply,
  kairoPending,
  mcpToolsForMode,
  modeButtonLabel,
  modelSearchQuery,
  onAutoToggleClick,
  openAddModelsPanel,
  openComposerImage,
  openVaultSurface,
  removeChip,
  removeComposerImage,
  editQueuedMessage,
  removeQueuedMessage,
  requestFullAccess,
  revealComposerTerminalPanel,
  runtimeDetail,
  runtimeHint,
  runtimeLabel,
  runtimeTargets,
  selectComposerModel,
  selectManageModelRow,
  selectMode,
  selectRuntimeTarget,
  selectedModelId,
  selectedModelLabel,
  selectedRuntimeSummary,
  selectionChipLabel,
  shell,
  showAddModelsEntry,
  showAddModelsPanel,
  showApprovalBanner,
  showComposerResume,
  composerResumeLabel,
  showComposerSteer,
  showComposerStop,
  showContextMenu,
  showDebugReproduceBanner,
  showCursorCatalog,
  showExtraPinnedRows,
  showFullAccessConsent,
  showModeMenu,
  showModelMenu,
  showRuntimeTargetsPanel,
  showToolsMenu,
  showVaultAction,
  speechCapture,
  switchToConsultativeAccess,
  syncComposerHeight,
  toggleContext,
  toggleRuntimeTargetsPanel,
  toggleSection,
  toggleVoiceCapture,
} = useAgentDockComposer();
</script>

<template>
  <AgentDockFullAccessConsent :show="showFullAccessConsent" :checked="fullAccessConsentChecked" @update:checked="fullAccessConsentChecked = $event" @cancel="cancelFullAccessConsent" @confirm="confirmFullAccessConsent" />
  <AgentDockComposerImageLightbox :image="enlargedComposerImage" @close="closeComposerImageLightbox" />
  <form
    class="agent-dock-composer"
    @submit="handleSubmit"
    @dragover="handleComposerDragOver"
    @dragleave="handleComposerDragLeave"
    @drop="handleComposerDrop"
  >
    <BriefingSurfaceFollowupPrompt />
    <AgentDockDebugReproduceBanner
      v-if="showDebugReproduceBanner && debugReproduceRequest"
      :request="debugReproduceRequest"
      :pending="shell.commandMutationState === 'submitting' || shell.agentStreamActive"
      @proceed="handleDebugReproduceProceed(debugReproduceRequest.messageId)"
      @dismiss="handleDebugReproduceDismiss"
    />
    <AgentDockApprovalBanner
      :show="showApprovalBanner"
      :can-approve="shell.canApproveIdeAgentRun"
      :reject-pending="shell.runMutationPending"
      @approve="handleApproveRun"
      @reject="handleRejectRun"
    />
    <div
      class="agent-dock-composer__shell"
      :class="composerShellClasses"
    >
      <div class="agent-dock-composer__card">
        <AgentDockComposerInput
          :set-input-ref="setInputRef"
          :draft="composerDraftModel"
          :composer-mode="composerMode"
          :operator-persona-name="OPERATOR_PERSONA_NAME"
          :placeholder="composerPlaceholder"
          :workspace-selected="Boolean(shell.currentWorkspace)"
          :attachment-chips="attachmentChips"
          :composer-images="composerImages"
          :queue-items="shell.ideComposerQueue"
          :queue-summary="shell.ideComposerQueueSummary"
          :activity-chips="composerActivityChips"
          :composer-queue-hint="composerQueueHint"
          :show-composer-resume="showComposerResume"
          :composer-resume-label="composerResumeLabel"
          :show-composer-steer="showComposerSteer"
          :show-composer-stop="showComposerStop"
          :can-submit-composer="canSubmitComposer"
          :composer-submit-label="composerSubmitLabel"
          :command-mutation-state="shell.commandMutationState"
          :run-mutation-state="shell.runMutationState"
          :kairo-pending="kairoPending"
          :speech-capture-supported="speechCapture.supported"
          :speech-capturing="speechCapture.capturing.value"
          :privacy-mode="shell.operatorPresenceSettings.privacy_mode"
          @update:draft="composerDraftModel = $event"
          @remove-chip="removeChip"
          @open-image="openComposerImage"
          @remove-image="removeComposerImage"
          @edit-queued="editQueuedMessage"
          @remove-queued="removeQueuedMessage"
          @steer-queued="handleSteerQueuedMessage"
          @sync-height="syncComposerHeight"
          @keydown="handleComposerKeydown"
          @paste="handleComposerPaste"
          @reveal-terminal="revealComposerTerminalPanel"
          @resume="handleResumeRun"
          @steer="handleSteer"
          @toggle-voice="toggleVoiceCapture"
          @stop="handleStopRun"
        >
          <template #toolbar>
            <AgentDockComposerToolbar
              :show-context-menu="showContextMenu"
              :show-tools-menu="showToolsMenu"
              :show-model-menu="showModelMenu"
              :show-mode-menu="showModeMenu"
              :show-add-models-panel="showAddModelsPanel"
              :show-runtime-targets-panel="showRuntimeTargetsPanel"
              :show-add-models-entry="showAddModelsEntry"
              :show-extra-pinned-rows="showExtraPinnedRows"
              :show-cursor-catalog="showCursorCatalog"
              :show-vault-action="showVaultAction"
              :attachment-chips="attachmentChips"
              :composer-image-count="composerImages.length"
              :mcp-tools-for-mode="mcpToolsForMode"
              :composer-mode="composerMode"
              :mode-options="MODE_OPTIONS"
              :mode-button-label="modeButtonLabel"
              :active-mode="activeMode"
              :is-full-access-agent="isFullAccessAgent"
              :execution-access-hint="executionAccessHint"
              :context-workspace="contextWorkspace"
              :context-selection="contextSelection"
              :context-terminal="contextTerminal"
              :context-ide="contextIde"
              :context-pinned="contextPinned"
              :has-terminal-snippet="hasTerminalSnippet"
              :selection-chip-label="selectionChipLabel"
              :runtime-detail="runtimeDetail"
              :runtime-label="runtimeLabel"
              :selected-runtime-summary="selectedRuntimeSummary"
              :runtime-targets="runtimeTargets"
              :selected-model-id="selectedModelId"
              :selected-model-label="selectedModelLabel"
              :auto-model-row="autoModelRow"
              :auto-toggle-checked="autoToggleChecked"
              :composer-picker-rows="composerPickerRows"
              :extra-pinned-rows="extraPinnedRows"
              :cursor-catalog-total="cursorCatalogTotal"
              :cursor-catalog-status="cursorCatalogStatus"
              :cursor-auth-line="cursorAuthLine"
              :cursor-stale-warning="cursorStaleWarning"
              :cursor-manage-rows="cursorManageRows"
              :cursor-catalog-count="cursorCatalogCount"
              :model-search-query="modelSearchQuery"
              :runtime-hint="runtimeHint"
              :can-convert-instructions="canConvertInstructions"
              @toggle-section="toggleSection"
              @toggle-context="toggleContext"
              @attach-files-media="attachFilesMedia"
              @convert-to-instructions="convertDraftToInstructions"
              @toggle-runtime-targets="toggleRuntimeTargetsPanel"
              @select-runtime-target="selectRuntimeTarget"
              @select-composer-model="selectComposerModel"
              @select-manage-model="selectManageModelRow"
              @open-add-models="openAddModelsPanel"
              @close-add-models="closeAddModelsPanel"
              @auto-toggle-click="onAutoToggleClick"
              @update:model-search-query="modelSearchQuery = $event"
              @select-mode="selectMode"
              @request-full-access="requestFullAccess"
              @switch-consultative="switchToConsultativeAccess"
              @open-vault="openVaultSurface"
            />
          </template>
        </AgentDockComposerInput>
      </div>
    </div>
    <AgentDockKairoComposerFooter
      :composer-mode="composerMode"
      :operator-persona-name="OPERATOR_PERSONA_NAME"
      :kairo-conversation-reply="kairoConversationReply"
      :kairo-conversation-error="kairoConversationError"
      :command-mutation-error="shell.commandMutationError"
      :run-mutation-error="shell.runMutationError"
      :workspace-selected="Boolean(shell.currentWorkspace)"
    />
  </form>
</template>
